Add documentation for flatpak
openSUSE/obs-docu pull request #183
Opened 2021-01-28 14:41 UTC by perlpunk

2021-02-04 07:15 UTC, tomschr requested changes
Thanks Tina for your pull request, much appreciated! :+1: 

I've left some suggestions (see below). They are mostly minor things (structure, spelling etc). Hope it helps. Let me know if you have any questions.

2021-02-04 07:15 UTC, tomschr commented on xml/obs_package_formats.xml
> +  For building an installable flatpak bundle, you need a
We should capitalize project names. Look for other occurances. :slightly_smiling_face: 

```suggestion
  For building an installable Flatpak bundle, you need a
```

2021-02-04 07:15 UTC, tomschr commented on xml/obs_package_formats.xml
> +  <filename>flatpak.yaml</filename> manifest.
I would be explicit here:

```suggestion
  <filename>flatpak.yaml</filename> manifest file.
```

2021-02-04 07:15 UTC, tomschr commented on xml/obs_package_formats.xml
> +   <title>&flatpak; Manifest</title>
I would give this example a filename.

2021-02-04 07:15 UTC, tomschr commented on xml/obs_package_formats.xml
> +  The base images (freedesktop, gnome, kde) are maintained in the
I would remove the parenthesis and use the project names. As an alternative, you can keep the parenthesis, but use a tag around the image names, for example, with `literal`: `<literal>kde</literal>`.

```suggestion
  The base images for Freedesktop, GNOME, or KDE are maintained in the
```

2021-02-04 16:46 UTC, perlpunk commented
Thanks @tomschr !
I think I addressed all of your suggestions :)

2021-02-11 10:44 UTC, perlpunk commented
Is there anything else I can do? :)

2021-02-17 20:14 UTC, perlpunk commented
@eduardoj made some suggestions, so I did a tiny restructure of the first paragraphs.

2021-02-18 07:59 UTC, merged

2021-02-19 09:52 UTC, perlpunk commented
When will this go live? Is there some automated deployment?
Still can't see it here https://openbuildservice.org/help/manuals/obs-user-guide/cha.obs.package_formats.html

2021-02-19 09:55 UTC, adrianschroeter commented
On Freitag, 19. Februar 2021, 10:52:36 CET Tina Müller (tinita) wrote:
> When will this go live? Is there some automated deployment?
> Still can't see it here https://openbuildservice.org/help/manuals/obs-user-guide/cha.obs.package_formats.html

it is live

-- 

Adrian Schroeter <adrian@suse.de>
Build Infrastructure Project Manager

SUSE Software Solutions Germany GmbH,  Maxfeldstr. 5, 90409 Nuernberg, Germany
(HRB 247165, AG München), Geschäftsführer: Felix Imendörffer

2021-02-19 10:05 UTC, perlpunk commented
Hm, then I wonder why I can't see the new entry. Did I miss something in my PR?

2021-02-19 10:09 UTC, adrianschroeter commented
On Freitag, 19. Februar 2021, 11:05:25 CET Tina Müller (tinita) wrote:
> Hm, then I wonder why I can't see the new entry. Did I miss something in my PR?

ah, sorry, mixed it up with your implementation in OBS code.

I will push new build of the documentation in next minutes ...

-- 

Adrian Schroeter <adrian@suse.de>
Build Infrastructure Project Manager

SUSE Software Solutions Germany GmbH,  Maxfeldstr. 5, 90409 Nuernberg, Germany
(HRB 247165, AG München), Geschäftsführer: Felix Imendörffer