spec file BuildConstraints examples
openSUSE/obs-docu pull request #285
Opened 2023-05-22 12:16 UTC by adrianschroeter

2023-05-22 15:23 UTC, hennevogel requested changes

2023-05-23 03:12 UTC, tserong commented
I've been experimenting with `#!BuildConstraint` today, and it looks like if a `_constraints` file is present, the values in that file will override the values from `#!BuildConstraint` in spec files. Maybe also add a note about values from `_constraints` taking precedence over what's in the spec files?

2023-05-23 03:32 UTC, tserong commented
Oh, also, `osc checkconstraints` seems to completely ignore `#!BuildConstraint`. Should that be documented too, or shall I go open a bug somewhere?

Thanks!

2023-06-07 11:47 UTC, darix commented
This PR should probably mention that you shouldnt mix _constriants and `#!BuildConstraints`

2023-06-29 12:17 UTC, adrianschroeter commented
> I've been experimenting with `#!BuildConstraint` today, and it looks like if a `_constraints` file is present, the values in that file will override the values from `#!BuildConstraint` in spec files. Maybe also worth adding a note about values from `_constraints` taking precedence over what's in the spec files?

the opposite is true meanwhile, it is part of the docu now

2023-06-29 12:18 UTC, adrianschroeter commented
> This PR should probably mention that you shouldnt mix _constriants and `#!BuildConstraint`

it is fine to combine that. It is not different as with mixing from project build config.

2023-06-29 12:18 UTC, adrianschroeter commented on xml/obs_build_job_constraints.xml
> +  also from the build descriptions, eg. in spec files. These can also be used
the docu is mentioning spec files and Dockerfile for now.

2023-06-29 12:19 UTC, merged

2023-06-29 14:19 UTC, tomschr commented on xml/obs_build_job_constraints.xml
> + <para>In addition to that some build receipe parsers support to parse constraints
I think a noun is missing after "the above". Where do you refer to? To a list/paragraph/...? If it's the last para, you could use "previous paragraph".

If it's something that is not easy to describe or further away, use `<xref linkend="..."/>` to refer to the respective block element.